README.md
lib/itamae-plugin-recipe-rbenv.rb
lib/itamae/plugin/recipe/rbenv.rb
lib/itamae/plugin/recipe/rbenv/system.rb

I want to install rbenv to other than `/usr/local/rbenv`
* Add rbenv_root configuration to node config file
* Tiny refactoring
node.yml
```yaml
rbenv:
rbenv_root: "/path/to/rbenv"
```
`rbenv_root` is shortcut method of `node[:rbenv][:rbenv_root]`
recipes/my_rbenv.rb
```ruby
include_recipe "rbenv::system"
require "itamae/plugin/recipe/rbenv"
execute "chown jenkins:drecom -R #{rbenv_root}" do
command "chown jenkins:jenkins -R #{rbenv_root}"
end
execute "chmod g+w -R #{rbenv_root}" do
command "chmod g+w -R #{rbenv_root}"
end
```

Add rbenv_root configuration to node config file

---

README.md
lib/itamae/plugin/recipe/rbenv/system.rb

Automatically install often used gems (ex. `bundler`) every time after `rbenv install`
cf. https://github.com/sstephenson/rbenv-default-gems
```yaml
rbenv-default-gems:
default-gems:
- bundler
- bcat ~>0.6
- rails --pre
revision: ead67889c91c53ad967f85f5a89d986fdb98f6fb
```

Support rbenv-default-gems

---

lib/itamae/plugin/recipe/rbenv/system.rb

If only `libffi-devel` , `openssl-devel` and `readline-devel` , doesn't run on Debian (Debian is other package name ...)
So I added Debian packages
https://github.com/sstephenson/ruby-build/wiki#suggested-build-environment
I checked these platforms
* CentOS 6.5
* Debian Wheezy

Support non CentOS packages

---

lib/itamae/plugin/recipe/rbenv/system.rb

I got method_missing error with `os` function on latest itamae (version 1.2.10), so use `node[:platform]` and it's working.

use node[:platform] instead of os[:family]

---

lib/itamae/plugin/recipe/rbenv/system.rb

I had the following error because  `git` resource requires git package implicitly.
Should itamae-plugin-recipe-rbenv depend on `git` package?
```
/home/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/itamae-1.2.15/lib/itamae/resource/git.rb:62:in `ensure_git_available': `git` command is not available. Please install git. (RuntimeError)
```

Add git package

---

README.md
lib/itamae/plugin/recipe/rbenv/system.rb

Support [rbenv-gem-rehash](https://github.com/sstephenson/rbenv-gem-rehash). This plugin automatically runs `rbenv rehash`.

Support rbenv-gem-rehash

---

lib/itamae/plugin/recipe/rbenv/install.rb

`include_recipe 'rbenv:user'`したときにデフォルトではsudoで実行されるので、
rbenv関連のファイルの所有者がrootになっています。
`node[:rbenv][:user]`が指定されていればそのユーザーを所有者とするように修正しました。

fix owner for a user

---

mrblib/mitamae
mrblib/mitamae/plugin

I use MItamae .
[README.md](https://github.com/k0kubun/itamae-plugin-recipe-rbenv#mitamae) writes ` Put this repository under ./plugins as git submodule.` .
But not working, Because directory structure is different.
MItamae include `plugins/{,m}itamae-plugin-recipe-#{name}/mrblib/{,m}itamae/plugin/recipe/#{name}`
https://github.com/k0kubun/mitamae/blob/master/mrblib/mitamae/plugin.rb#L32
But this recipe path is `mitamae/lib/itamae/plugin/recipe`.
I Fixed symbolic link.
Please check PR.

create symbolic link beacuse use mitamae

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

Hello,
I created a this Pull Request. This is a little appendix to Readme.md.
Because I got stuck in rbenv installation.
↓↓↓ Here is my episode.
---
I use this plugin toward Amazon linux
I built Ruby on Rails environment while I saw Readme.md node.yml usage.
First, I wrote node.yml
```
rbenv:
global:
2.3.3
versions:
- 2.3.3
scheme: https
```
But I run itamae, when I happened a error.
```
INFO : Starting Itamae...
INFO : Loading node data from /Users/kawakubox/Workspace/generic-recipe/roles/rails/node.yml...
INFO : Recipe: /Users/kawakubox/Workspace/generic-recipe/roles/rails/default.rb
INFO :   Recipe: /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/itamae-plugin-recipe-rbenv-0.6.3/lib/itamae/plugin/recipe/rbenv/system.rb
INFO :     Recipe: …
```

Add platform sample in node.yml usage

---

lib/itamae/plugin/recipe/rbenv/install.rb

```
$ rbenv versions
system
2.1.10
$ rbenv versions | grep 2.1.1
2.1.10
$ rbenv versions --bare | grep -w 2.1.1
```

Fix ruby version checking for two-digits

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

This condition is intended for Ubuntu.
- 323424d0f3743f1ae9c3961b201b53b6a4935fa6
- 80d3d37d6bd923561f080070622ff3729f7949d1
I've got following error on Debian stretch.
```
ERROR :           stdout | パッケージリストを読み込んでいます...
ERROR :           stdout | 依存関係ツリーを作成しています...
ERROR :           stdout | 状態情報を読み取っています...
ERROR :           stderr | E: パッケージ libgdbm5 が見つかりません
ERROR :           Command `DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold'  install libgdbm5` failed. (exit status: 100)
ERROR :         package[libgdbm5] Failed.
```
In Debian stretch, the `node[:platform_version]` is `"9.5"` and it's greater than `"18.04"`.
```
$ mruby -e 'p "9.5" >= "18.04"'
true
```
But libgdbm5 is not in Debian stretch's repository.

Add guard condition for packages to fix error on Debian

---

lib/itamae/plugin/recipe/rbenv/install.rb

This PR makes the user of this library add arbitrary github hosted plugin installs to rbenv.
For example, when one wants to add `rbenv-sudo` (https://github.com/dcarley/rbenv-sudo), one can write following node information to achieve it.
```yaml
rbenv:
plugins:
- rbenv-sudo
rbenv-sudo:
install: true
group: dcarley
```
Since this gem already takes care of installing some plugins (`ruby-build` and `rbenv-default-gems`), I thought it would be convenient for user if this gem takes care of the other plugins also.
Any opinion...?

Support arbitrary plugin install

---

lib/itamae/plugin/recipe/rbenv/install.rb

This patch consists of the following two points,
- Fixed a typo in splitting plugin name to owner and repository name.
- Determine without `node[:name]` variable whether to install a plugin.
The first point may be clear but we need to explain the second point.
Current README says that we can install rbenv plugins like following node configuration,
```yaml
rbenv:
plugins:
dcarley/rbenv-sudo:
revision: master
```
However, we cannot install because of `node[name]` variable (in this situation, `node[:rbenv-sudo]`) returns nil.
I think it's not good to refer `node[name]` in `define :rbenv_plugin` block. So I added install parameter to the statement.
By doing this, we can let Itamae prevent to install plugin only if install parameter is set false explicitly.

Make installing arbitrary rbenv plugin feature run properly

---

lib/itamae/plugin/recipe/rbenv/install.rb

This plugin always executes `rbenv global` because the `not_if` does not work.
It specifies `rbenv version --bare | grep -x #{version}`.
I guess the `--bare` option expects to print only the version name, like "2.7.0", but it also print the origin.
```bash
$ rbenv version --bare
2.7.0 (set by /home/pocke/.rbenv/version)
```
Because `rbenv version` command does not have `--bare` option.
It does not match `grep -x #{vesion}`, because the `-x` option means "the whole line".
Use `rbenv global` instaed of `rbenv version --bare`.
First, I tried using `rbenv version-name`, because it is suggested by the help.
```bash
$ rbenv version --help
Usage: rbenv version
Shows the currently selected Ruby version and how it was
selected. To obtain only the version string, use `rbenv
version-name'.
```
But I …

Avoid unnecessary `rbenv global`

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

I got the following error with plain fedora31 instance on AWS.
```
[18.176.170.223]   INFO :       execute[rbenv install 2.5.7] executed will change from 'false' to 'true'
[18.176.170.223]  ERROR :         stderr | Downloading ruby-2.5.7.tar.bz2...
[18.176.170.223]  ERROR :         stderr | -> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.bz2
[18.176.170.223]  ERROR :         stderr | Installing ruby-2.5.7...
[18.176.170.223]  ERROR :         stderr |
[18.176.170.223]  ERROR :         stderr | BUILD FAILED (Fedora 31 using ruby-build 20200224)
[18.176.170.223]  ERROR :         stderr |
[18.176.170.223]  ERROR :         stderr | Inspect or clean up the working tree at /tmp/ruby-build.20200302052635.21585.NPkDCq
[18.176.170.223]  ERROR :         stderr | Results logged to …
```

Added make to RedHat platforms

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

It was required *-dev definitions for Ruby < 2.7.

Added Subversion

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

debian testing and sid did return "testing" and "sid" string instead of version number.

Added debian testing condition

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

RHEL8 didn't provide `libyaml-devel`

Remove libyaml-devel with rhel8

---

lib/itamae/plugin/recipe/rbenv/system.rb

The git protocol has been discontinued.
It has been replaced with the use of HTTPS.
Ref:https://github.blog/2021-09-01-improving-git-protocol-security-github/

Abolition git protocol

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

I forgot why I removed `libyaml-devel` from CentOS 7 at https://github.com/itamae-plugins/itamae-plugin-recipe-rbenv/pull/35 (It's wrong title...)
I checked it on RHEL8, CentOS 7 and Fedora 36. `libyaml-devel` is provided the all of RedHat distributions that are maintained now. 
I removed needless condition for CentOS 7.

Install libyaml for the all of RedHat distributions

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

```
[rhel9.rubyci.org]  INFO :         package[gdbm-devel] installed will change from 'false' to 'true'
[rhel9.rubyci.org] ERROR :           stdout | Updating Subscription Management repositories.
[rhel9.rubyci.org] ERROR :           stdout | Unable to read consumer identity
[rhel9.rubyci.org] ERROR :           stdout |
[rhel9.rubyci.org] ERROR :           stdout | This system is not registered with an entitlement server. You can use subscription-manager to register.
[rhel9.rubyci.org] ERROR :           stdout |
[rhel9.rubyci.org] ERROR :           stdout | Last metadata expiration check: 0:22:27 ago on Thu 26 Jan 2023 07:40:23 AM UTC.
[rhel9.rubyci.org] ERROR :           stdout | No match for argument: gdbm-devel
[rhel9.rubyci.org] ERROR :           stderr | Error: Unable to find a …
```

gdbm-devel is not available on RHEL9

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

We can install `gdbm-devel` and `libyaml-devel` after:
```
$ sudo yum-config-manager --enable codeready-builder-for-rhel-9-rhui-rpms
```

Revert "Merge pull request #41 from itamae-plugins/rhel9-gdbm"

---

lib/itamae/plugin/recipe/rbenv/dependency.rb
lib/itamae/plugin/recipe/rbenv/development_dependency.rb

Hello,
This pull request adds support for the Raspbian (Raspberry Pi OS).
Almost the same as Debian, but since `libgdbm3` is not available and `libreadline6-dev` is redirected to `libreadline-dev`, the following part is required.
https://github.com/itamae-plugins/itamae-plugin-recipe-rbenv/blob/ea45254cfa179aa195314a7dd5aac92bbce0b74d/lib/itamae/plugin/recipe/rbenv/dependency.rb#L17-L19
```console
$ sudo apt install libgdbm3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgdbm3
```
```console
$ sudo apt install libreadline6-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
libreadline-dev is …
```

Support Raspbian (Raspberry Pi OS)

---

lib/itamae/plugin/recipe/rbenv/dependency.rb

Fedora 40 uses `zlib-ng-compat` instead of `zlib`.

Added support Fedora 40
